version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: silvet-db
    environment:
      POSTGRES_DB: silvet_db
      POSTGRES_USER: silvet_user
      POSTGRES_PASSWORD: silvet_password
    ports:
      - "5432:5432"
    volumes:
      - ./infra/init-schemas.sql:/docker-entrypoint-initdb.d/init-schemas.sql