openapi: 3.0.3
info:
  title: Vestris - Módulo Espécies
  description: API de Taxonomia do Silvet
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor Local

# Importando os caminhos
paths:
  /api/v1/especies:
    $ref: './paths/especies.yml#/paths/~1api~1v1~1especies'

  /api/v1/especies/{id}:
    $ref: './paths/especies.yml#/paths/~1api~1v1~1especies~1{id}'

components:
  schemas:
    EspecieRequest:
      $ref: "./components/schemas.yml#/EspecieRequest"
    EspecieResponse:
      $ref: "./components/schemas.yml#/EspecieResponse"
    ApiResponseEspecie:
      $ref: "./components/schemas.yml#/ApiResponseEspecie"
    ApiResponseListaEspecie:
      $ref: "./components/schemas.yml#/ApiResponseListaEspecie"