spring.profiles.active=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/vestris_db
spring.datasource.username=vestris_user
spring.datasource.password=vestris_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs