openapi: 3.0.3
info:
  title: Vestris - Módulo Usuários
  description: Autenticação e Gestão de Contas
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor Local

paths:
  /api/v1/auth/registro:
    $ref: "./paths/registro.yml"
  /api/v1/auth/login:
    $ref: "./paths/login.yml"

components:
  schemas:
    RegistroRequest:
      $ref: "./components/schemas.yml#/RegistroRequest"
    LoginRequest:
      $ref: "./components/schemas.yml#/VacinaRequest"
    UsuarioResponse:
      $ref: "./components/schemas.yml#/UsuarioResponse"
    TokenResponse:
      $ref: "./components/schemas.yml#/TokenResponse"
    ApiResponseUsuario:
      $ref: "./components/schemas.yml#/ApiResponseUsuario"
    ApiResponseToken:
      $ref: "./components/schemas.yml#/ApiResponseToken"
